### ISSUE TITLE
USWDS - Build tools: Axe error on `npm test`.

### ISSUE THREAD

**Issue by mejiaj** [uswds/uswds-site#971]
## Description
`npm test` errors out on the latest code on `master` branch.

## Steps to reproduce the issue

1. `npm install`
2. `npm run build`
3. `npm test`

## Additional information [optional]
<details>
<summary>npm error</summary>
<p>

```bash
> node config/run-axe.js

Static file server is listening at http://localhost:55607.
Chrome is debuggable on http://localhost:55613.
Running aXe on:
  /page-templates/docs/ ERROR: https://www.google-analytics.com/analytics.js failed to load
Unhandled Rejection at: Promise {
  <rejected> Error: WebSocket is not open: readyState 2 (CLOSING)
      at sendAfterClose (/Users/jamesmejia/web/uswds-site/node_modules/ws/lib/websocket.js:729:17)
      at WebSocket.send (/Users/jamesmejia/web/uswds-site/node_modules/ws/lib/websocket.js:339:7)
      at Chrome._enqueueCommand (/Users/jamesmejia/web/uswds-site/node_modules/chrome-remote-interface/lib/chrome.js:281:18)
      at /Users/jamesmejia/web/uswds-site/node_modules/chrome-remote-interface/lib/chrome.js:87:22
      at new Promise (<anonymous>)
      at Chrome.send (/Users/jamesmejia/web/uswds-site/node_modules/chrome-remote-interface/lib/chrome.js:86:20)
      at Object.handler [as evaluate] (/Users/jamesmejia/web/uswds-site/node_modules/chrome-remote-interface/lib/api.js:32:23)
      at Chrome.<anonymous> (/Users/jamesmejia/web/uswds-site/config/run-axe.js:120:17)
      at Chrome.emit (events.js:210:5)
      at Chrome._handleMessage (/Users/jamesmejia/web/uswds-site/node_modules/chrome-remote-interface/lib/chrome.js:270:18)
} reason: Error: WebSocket is not open: readyState 2 (CLOSING)
    at sendAfterClose (/Users/jamesmejia/web/uswds-site/node_modules/ws/lib/websocket.js:729:17)
    at WebSocket.send (/Users/jamesmejia/web/uswds-site/node_modules/ws/lib/websocket.js:339:7)
    at Chrome._enqueueCommand (/Users/jamesmejia/web/uswds-site/node_modules/chrome-remote-interface/lib/chrome.js:281:18)
    at /Users/jamesmejia/web/uswds-site/node_modules/chrome-remote-interface/lib/chrome.js:87:22
    at new Promise (<anonymous>)
    at Chrome.send (/Users/jamesmejia/web/uswds-site/node_modules/chrome-remote-interface/lib/chrome.js:86:20)
    at Object.handler [as evaluate] (/Users/jamesmejia/web/uswds-site/node_modules/chrome-remote-interface/lib/api.js:32:23)
    at Chrome.<anonymous> (/Users/jamesmejia/web/uswds-site/config/run-axe.js:120:17)
    at Chrome.emit (events.js:210:5)
    at Chrome._handleMessage (/Users/jamesmejia/web/uswds-site/node_modules/chrome-remote-interface/lib/chrome.js:270:18)
Terminating with exit code 1.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! uswds-site@ axe: `node config/run-axe.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the uswds-site@ axe script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

</p>
</details> 

<details>
<summary>Debug log</summary>
<p>

```bash
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/Users/jamesmejia/.nvm/versions/node/v13.0.1/bin/node',
1 verbose cli   '/Users/jamesmejia/.nvm/versions/node/v13.0.1/bin/npm',
1 verbose cli   'run',
1 verbose cli   'axe'
1 verbose cli ]
2 info using npm@6.14.2
3 info using node@v13.0.1
4 verbose run-script [ 'preaxe', 'axe', 'postaxe' ]
5 info lifecycle uswds-site@~preaxe: uswds-site@
6 info lifecycle uswds-site@~axe: uswds-site@
7 verbose lifecycle uswds-site@~axe: unsafe-perm in lifecycle true
8 verbose lifecycle uswds-site@~axe: PATH: /Users/jamesmejia/.nvm/versions/node/v13.0.1/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/jamesmejia/web/uswds-site/node_modules/.bin:/Users/jamesmejia/.nvm/versions/node/v13.0.1/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/jamesmejia/web/uswds-site/node_modules/.bin:/Users/jamesmejia/.rvm/gems/ruby-2.6.3/bin:/Users/jamesmejia/.rvm/gems/ruby-2.6.3@global/bin:/Users/jamesmejia/.rvm/rubies/ruby-2.6.3/bin:/Users/jamesmejia/.rvm/bin:/usr/local/opt/php@7.3/sbin:/usr/local/opt/php@7.3/bin:/usr/local/lib/ruby/bin:/Users/jamesmejia/.nvm/versions/node/v13.0.1/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/jamesmejia/.composer/vendor/bin
9 verbose lifecycle uswds-site@~axe: CWD: /Users/jamesmejia/web/uswds-site
10 silly lifecycle uswds-site@~axe: Args: [ '-c', 'node config/run-axe.js' ]
11 silly lifecycle uswds-site@~axe: Returned: code: 1  signal: null
12 info lifecycle uswds-site@~axe: Failed to exec axe script
13 verbose stack Error: uswds-site@ axe: `node config/run-axe.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/Users/jamesmejia/.nvm/versions/node/v13.0.1/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:210:5)
13 verbose stack     at ChildProcess.<anonymous> (/Users/jamesmejia/.nvm/versions/node/v13.0.1/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:210:5)
13 verbose stack     at maybeClose (internal/child_process.js:1028:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
14 verbose pkgid uswds-site@
15 verbose cwd /Users/jamesmejia/web/uswds-site
16 verbose Darwin 19.5.0
17 verbose argv "/Users/jamesmejia/.nvm/versions/node/v13.0.1/bin/node" "/Users/jamesmejia/.nvm/versions/node/v13.0.1/bin/npm" "run" "axe"
18 verbose node v13.0.1
19 verbose npm  v6.14.2
20 error code ELIFECYCLE
21 error errno 1
22 error uswds-site@ axe: `node config/run-axe.js`
22 error Exit status 1
23 error Failed at the uswds-site@ axe script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```
</p>
</details>

**Comment by thisisdano** [comment]
This is no longer an issue
